const Joi = require('joi');

export const editLeaveRequestSchemaValidator = Joi.object().keys({
    // we need to ensure that _id is a valid mongoDB ObjectId
    _id: Joi.string().required(),
    fullName: Joi.string().pattern(/^[A-Za-z\s-]+$/).required(),
    staffId: Joi.string().required(),
    phone: Joi.string().required(),
    email: Joi.string().email().required(),
    role: Joi.string().required().valid(
        'Admin',
        'SuperAdmin',
        'User',
        'Accountant',
        'Generator Technician',
        'Procurement Officer',
        'Lawyer',
        'Driver',
        'Field Supervisor',
        'Security Officer'
    ).insensitive(),
    leaveType: Joi.string().required().valid(
        "Annual",
        "Casual",
        "Compassionate",
        "Emergency",
        "Maternity",
        "Paternity",
        "Sick",
        "Study",
        "Leave without Pay",
        "Others",
    ),
    startDate: Joi.date().required(),
    endDate: Joi.date().required(),
    leaveReason: Joi.string().required().valid(
        "Accident",
        "Annual",
        "Appointment",
        "Bereavement",
        "Burial",
        "Emergency",
        "Family Related",
        "Personal",
        "Medical CheckUp",
        "Medical",
        "Surgery",
        "Wedding",
        "Confidential",
    ),
    duration: Joi.number().required(),
    currentBalance: Joi.number().required(),
    newBalance: Joi.number().required(),
    saveAsDraft: Joi.boolean().required(),
    status: Joi.string().required().valid('Requested', 'Draft'),
});