const Joi = require('joi');

export const userSchemaValidator = Joi.object().keys({
    title: Joi.string().required(),
    firstName: Joi.string().required(),
    middleName: Joi.string().optional(),
    lastName: Joi.string().required(),
    email: Joi.string().email().required(),
    phone: Joi.string().required(),
    dob: Joi.date().required(),
    gender: Joi.string().required().valid('Male', 'Female'),
    maritalStatus: Joi.string().required().valid('Single', 'Married', 'Divorced'),
    religion: Joi.string().required().valid('Christianity', 'Islam', 'Others'),
    country: Joi.string().required(),
    state: Joi.string().required(),
    lga: Joi.string().required(),
    nextOfKin: Joi.string().required(),
    nextOfKinPhone: Joi.string().required(),
    nextOfKinRelationship: Joi.string().required().valid(
        'Father',
        'Mother',
        'Brother',
        'Sister',
        'Son',
        'Daughter',
        'Spouse',
        'Uncle',
        'Aunt',
        'Cousin',
        'Nephew',
        'Niece',
        'Grandfather',
        'Grandmother',
        'Others',
    ),
    address: Joi.string().required(),
    stateOfResidence: Joi.string().required(),
    employmentType: Joi.string().required().valid('FullTime', 'Contract', 'Trainee'),
    role: Joi.string().required().valid('Admin', 'SuperAdmin', 'User', 'Accountant', 'Generator Technician', 'Procurement Officer', 'Lawyer', 'Driver', 'Field Supervisor', 'Security Officer'),
    siteState: Joi.string().when('role', {
        is: Joi.string().valid('Field Supervisor', 'Generator Technician'),
        then: Joi.string().required(),
        otherwise: Joi.string().optional().allow('', null),
    }),
    cluster: Joi.string().when('role', {
        is: Joi.string().valid('Field Supervisor', 'Generator Technician'),
        then: Joi.string().required(),
        otherwise: Joi.string().optional().allow('', null),
    }),
    siteID: Joi.array().items(Joi.string()).when('role', {
        is: Joi.string().valid('Field Supervisor', 'Generator Technician'),
        then: Joi.array().min(1).required(),
        otherwise: Joi.array().optional().allow('', null),
    }),
});