export const statesAndLGAs = {
    Abia: [
        "Aba North",
        "Aba South",
        "Arochukwu",
        "Bende",
        "Ikwuano",
        "Isiala-Ngwa North",
        "Isiala-Ngwa South",
        "Isuikwato",
        "Obi Nwa",
        "Ohafia",
        "Osisioma",
        "Ngwa",
        "Ugwunagbo",
        "Ukwa East",
        "Ukwa West",
        "Umuahia North",
        "Umuahia South",
        "Umu-Neochi"
    ],
    Adamawa: [
        "Demsa",
        "Fufore",
        "Ganaye",
        "Gireri",
        "Gombi",
        "Guyuk",
        "Hong",
        "Jada",
        "Lamurde",
        "Madagali",
        "Maiha",
        "Mayo-Belwa",
        "Michika",
        "Mubi North",
        "Mubi South",
        "Numan",
        "Shelleng",
        "Song",
        "Toungo",
        "Yola North",
        "Yola South"
    ],
    Anambra: [
        "Aguata",
        "Anambra East",
        "Anambra West",
        "Anaocha",
        "Awka North",
        "Awka South",
        "Ayamelum",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili south",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Onitsha North",
        "Onitsha South",
        "Orumba North",
        "Orumba South",
        "Oyi"
    ],
    "Akwa Ibom": [
        "Abak",
        "Eastern Obolo",
        "Eket",
        "Esit Eket",
        "Essien Udim",
        "Etim Ekpo",
        "Etinan",
        "Ibeno",
        "Ibesikpo Asutan",
        "Ibiono Ibom",
        "Ika",
        "Ikono",
        "Ikot Abasi",
        "Ikot Ekpene",
        "Ini",
        "Itu",
        "Mbo",
        "Mkpat Enin",
        "Nsit Atai",
        "Nsit Ibom",
        "Nsit Ubium",
        "Obot Akara",
        "Okobo",
        "Onna",
        "Oron",
        "Oruk Anam",
        "Udung Uko",
        "Ukanafun",
        "Uruan",
        "Urue-Offong/Oruko ",
        "Uyo"
    ],
    Bauchi: [
        "Alkaleri",
        "Bauchi",
        "Bogoro",
        "Damban",
        "Darazo",
        "Dass",
        "Ganjuwa",
        "Giade",
        "Itas/Gadau",
        "Jama'are",
        "Katagum",
        "Kirfi",
        "Misau",
        "Ningi",
        "Shira",
        "Tafawa-Balewa",
        "Toro",
        "Warji",
        "Zaki"
    ],
    Bayelsa: [
        "Brass",
        "Ekeremor",
        "Kolokuma/Opokuma",
        "Nembe",
        "Ogbia",
        "Sagbama",
        "Southern Jaw",
        "Yenegoa"
    ],
    Benue: [
        "Ado",
        "Agatu",
        "Apa",
        "Buruku",
        "Gboko",
        "Guma",
        "Gwer East",
        "Gwer West",
        "Katsina-Ala",
        "Konshisha",
        "Kwande",
        "Logo",
        "Makurdi",
        "Obi",
        "Ogbadibo",
        "Oju",
        "Okpokwu",
        "Ohimini",
        "Oturkpo",
        "Tarka",
        "Ukum",
        "Ushongo",
        "Vandeikya"
    ],
    Borno: [
        "Abadam",
        "Askira/Uba",
        "Bama",
        "Bayo",
        "Biu",
        "Chibok",
        "Damboa",
        "Dikwa",
        "Gubio",
        "Guzamala",
        "Gwoza",
        "Hawul",
        "Jere",
        "Kaga",
        "Kala/Balge",
        "Konduga",
        "Kukawa",
        "Kwaya Kusar",
        "Mafa",
        "Magumeri",
        "Maiduguri",
        "Marte",
        "Mobbar",
        "Monguno",
        "Ngala",
        "Nganzai",
        "Shani"
    ],
    "Cross River": [
        "Akpabuyo",
        "Odukpani",
        "Akamkpa",
        "Biase",
        "Abi",
        "Ikom",
        "Yarkur",
        "Odubra",
        "Boki",
        "Ogoja",
        "Yala",
        "Obanliku",
        "Obudu",
        "Calabar South",
        "Etung",
        "Bekwara",
        "Bakassi",
        "Calabar Municipality"
    ],
    Delta: [
        "Oshimili",
        "Aniocha",
        "Aniocha South",
        "Ika South",
        "Ika North-East",
        "Ndokwa West",
        "Ndokwa East",
        "Isoko south",
        "Isoko North",
        "Bomadi",
        "Burutu",
        "Ughelli South",
        "Ughelli North",
        "Ethiope West",
        "Ethiope East",
        "Sapele",
        "Okpe",
        "Warri North",
        "Warri South",
        "Uvwie",
        "Udu",
        "Warri Central",
        "Ukwani",
        "Oshimili North",
        "Patani"
    ],
    Ebonyi: [
        "Edda",
        "Afikpo",
        "Onicha",
        "Ohaozara",
        "Abakaliki",
        "Ishielu",
        "lkwo",
        "Ezza",
        "Ezza South",
        "Ohaukwu",
        "Ebonyi",
        "Ivo"
    ],
    Enugu: [
        "Enugu South,",
        "Igbo-Eze South",
        "Enugu North",
        "Nkanu",
        "Udi Agwu",
        "Oji-River",
        "Ezeagu",
        "IgboEze North",
        "Isi-Uzo",
        "Nsukka",
        "Igbo-Ekiti",
        "Uzo-Uwani",
        "Enugu Eas",
        "Aninri",
        "Nkanu East",
        "Udenu."
    ],
    Edo: [
        "Esan North-East",
        "Esan Central",
        "Esan West",
        "Egor",
        "Ukpoba",
        "Central",
        "Etsako Central",
        "Igueben",
        "Oredo",
        "Ovia SouthWest",
        "Ovia South-East",
        "Orhionwon",
        "Uhunmwonde",
        "Etsako East",
        "Esan South-East"
    ],
    Ekiti: [
        "Ado",
        "Ekiti-East",
        "Ekiti-West",
        "Emure/Ise/Orun",
        "Ekiti South-West",
        "Ikere",
        "Irepodun",
        "Ijero,",
        "Ido/Osi",
        "Oye",
        "Ikole",
        "Moba",
        "Gbonyin",
        "Efon",
        "Ise/Orun",
        "Ilejemeje."
    ],
    FCT: [
        "Abaji",
        "Abuja Municipal",
        "Bwari",
        "Gwagwalada",
        "Kuje",
        "Kwali"
    ],
    Gombe: [
        "Akko",
        "Balanga",
        "Billiri",
        'Dukku',
        "Kaltungo",
        "Kwami",
        "Shomgom",
        "Funakaye",
        "Gombe",
        "Nafada/Bajoga",
        "Yamaltu/Delta."
    ],
    Imo: [
        "Aboh-Mbaise",
        "Ahiazu-Mbaise",
        "Ehime-Mbano",
        "Ezinihitte",
        "Ideato North",
        "Ideato South",
        "Ihitte/Uboma",
        "Ikeduru",
        "Isiala Mbano",
        "Isu",
        "Mbaitoli",
        "Mbaitoli",
        "Ngor-Okpala",
        "Njaba",
        "Nwangele",
        "Nkwerre",
        "Obowo",
        "Oguta",
        "Ohaji/Egbema",
        "Okigwe",
        "Orlu",
        "Orsu",
        "Oru East",
        "Oru West",
        "Owerri-Municipal",
        "Owerri North",
        "Owerri West"
    ],
    Jigawa: [
        "Auyo",
        "Babura",
        "Birni Kudu",
        "Biriniwa",
        "Buji",
        "Dutse",
        "Gagarawa",
        "Garki",
        "Gumel",
        "Guri",
        "Gwaram",
        "Gwiwa",
        "Hadejia",
        "Jahun",
        "Kafin Hausa",
        "Kaugama Kazaure",
        "Kiri Kasamma",
        "Kiyawa",
        "Maigatari",
        "Malam Madori",
        "Miga",
        "Ringim",
        "Roni",
        "Sule-Tankarkar",
        "Taura",
        "Yankwashi"
    ],
    Kaduna: [
        "Birni-Gwari",
        "Chikun",
        "Giwa",
        "Igabi",
        "Ikara",
        "jaba",
        "Jema'a",
        "Kachia",
        "Kaduna North",
        "Kaduna South",
        "Kagarko",
        "Kajuru",
        "Kaura",
        "Kauru",
        "Kubau",
        "Kudan",
        "Lere",
        "Makarfi",
        "Sabon-Gari",
        "Sanga",
        "Soba",
        "Zango-Kataf",
        "Zaria"
    ],
    Kano: [
        "Ajingi",
        "Albasu",
        "Bagwai",
        "Bebeji",
        "Bichi",
        "Bunkure",
        "Dala",
        "Dambatta",
        "Dawakin Kudu",
        "Dawakin Tofa",
        "Doguwa",
        "Fagge",
        "Gabasawa",
        "Garko",
        "Garum",
        "Mallam",
        "Gaya",
        "Gezawa",
        "Gwale",
        "Gwarzo",
        "Kabo",
        "Kano Municipal",
        "Karaye",
        "Kibiya",
        "Kiru",
        "kumbotso",
        "Ghari",
        "Kura",
        "Madobi",
        "Makoda",
        "Minjibir",
        "Nasarawa",
        "Rano",
        "Rimin Gado",
        "Rogo",
        "Shanono",
        "Sumaila",
        "Takali",
        "Tarauni",
        "Tofa",
        "Tsanyawa",
        "Tudun Wada",
        "Ungogo",
        "Warawa",
        "Wudil"
    ],
    Katsina: [
        "Bakori",
        "Batagarawa",
        "Batsari",
        "Baure",
        "Bindawa",
        "Charanchi",
        "Dandume",
        "Danja",
        "Dan Musa",
        "Daura",
        "Dutsi",
        "Dutsin-Ma",
        "Faskari",
        "Funtua",
        "Ingawa",
        "Jibia",
        "Kafur",
        "Kaita",
        "Kankara",
        "Kankia",
        "Katsina",
        "Kurfi",
        "Kusada",
        "Mai'Adua",
        "Malumfashi",
        "Mani",
        "Mashi",
        "Matazuu",
        "Musawa",
        "Rimi",
        "Sabuwa",
        "Safana",
        "Sandamu",
        "Zango"
    ],
    Kebbi: [
        "Aleiro",
        "Arewa-Dandi",
        "Argungu",
        "Augie",
        "Bagudo",
        "Birnin Kebbi",
        "Bunza",
        "Dandi",
        "Fakai",
        "Gwandu",
        "Jega",
        "Kalgo",
        "Koko/Besse",
        "Maiyama",
        "Ngaski",
        "Sakaba",
        "Shanga",
        "Suru",
        "Wasagu/Danko",
        "Yauri",
        "Zuru"
    ],
    Kogi: [
        "Adavi",
        "Ajaokuta",
        "Ankpa",
        "Bassa",
        "Dekina",
        "Ibaji",
        "Idah",
        "Igalamela-Odolu",
        "Ijumu",
        "Kabba/Bunu",
        "Kogi",
        "Lokoja",
        "Mopa-Muro",
        "Ofu",
        "Ogori/Mangongo",
        "Okehi",
        "Okene",
        "Olamabolo",
        "Omala",
        "Yagba East",
        "Yagba West"
    ],
    Kwara: [
        "Asa",
        "Baruten",
        "Edu",
        "Ekiti",
        "Ifelodun",
        "Ilorin East",
        "Ilorin West",
        "Irepodun",
        "Isin",
        "Kaiama",
        "Moro",
        "Offa",
        "Oke-Ero",
        "Oyun",
        "Pategi"
    ],
    Lagos: [
        "Agege",
        "Ajeromi-Ifelodun",
        "Alimosho",
        "Amuwo-Odofin",
        "Apapa",
        "Badagry",
        "Epe",
        "Eti-Osa",
        "Ibeju/Lekki",
        "Ifako-Ijaye",
        "Ikeja",
        "Ikorodu",
        "Kosofe",
        "Lagos Island",
        "Lagos Mainland",
        "Mushin",
        "Ojo",
        "Oshodi-Isolo",
        "Shomolu",
        "Surulere"
    ],
    Nasarawa: [
        "Akwanga",
        "Awe",
        "Doma",
        "Karu",
        "Keana",
        "Keffi",
        "Kokona",
        "Lafia",
        "Nasarawa",
        "Nasarawa-Eggon",
        "Obi",
        "Toto",
        "Wamba"
    ],
    Niger: [
        "Agaie",
        "Agwara",
        "Bida",
        "Borgu",
        "Bosso",
        "Chanchaga",
        "Edati",
        "Gbako",
        "Gurara",
        "Katcha",
        "Kontagora",
        "Lapai",
        "Lavun",
        "Magama",
        "Mariga",
        "Mashegu",
        "Mokwa",
        "Muya",
        "Pailoro",
        "Rafi",
        "Rijau",
        "Shiroro",
        "Suleja",
        "Tafa",
        "Wushishi"
    ],
    Ogun: [
        "Abeokuta North",
        "Abeokuta South",
        "Ado-Odo/Ota",
        "Yewa North",
        "Yewa South",
        "Ewekoro",
        "Ifo",
        "Ijebu East",
        "Ijebu North",
        "Ijebu North East",
        "Ijebu Ode",
        "Ikenne",
        "Imeko-Afon",
        "Ipokia",
        "Obafemi-Owode",
        "Ogun Waterside",
        "Odeda",
        "Odogbolu",
        "Remo North",
        "Shagamu"
    ],
    Ondo: [
        "Akoko North East",
        "Akoko North West",
        "Akoko South Akure East",
        "Akoko South West",
        "Akure North",
        "Akure South",
        "Ese-Odo",
        "Idanre",
        "Ifedore",
        "Ilaje",
        "Ile-Oluji",
        "Okeigbo",
        "Irele",
        "Odigbo",
        "Okitipupa",
        "Ondo East",
        "Ondo West",
        "Ose",
        "Owo"
    ],
    Osun: [
        "Aiyedade",
        "Aiyedire",
        "Atakumosa East",
        "Atakumosa West",
        "Boluwaduro",
        "Boripe",
        "Ede North",
        "Ede South",
        "Egbedore",
        "Ejigbo",
        "Ife Central",
        "Ife East",
        "Ife North",
        "Ife South",
        "Ifedayo",
        "Ifelodun",
        "Ila",
        "Ilesha East",
        "Ilesha West",
        "Irepodun",
        "Irewole",
        "Isokan",
        "Iwo",
        "Obokun",
        "Odo-Otin",
        "Ola-Oluwa",
        "Olorunda",
        "Oriade",
        "Orolu",
        "Osogbo"
    ],
    Oyo: [
        "Afijio",
        "Akinyele",
        "Atiba",
        "Atisbo",
        "Egbeda",
        "Ibadan Central",
        "Ibadan North",
        "Ibadan North West",
        "Ibadan South East",
        "Ibadan South West",
        "Ibarapa Central",
        "Ibarapa East",
        "Ibarapa North",
        "Ido",
        "Irepo",
        "Iseyin",
        "Itesiwaju",
        "Iwajowa",
        "Kajola",
        "Lagelu Ogbomosho North",
        "Ogbomosho South",
        "Ogo Oluwa",
        "Olorunsogo",
        "Oluyole",
        "Ona-Ara",
        "Orelope",
        "Ori Ire",
        "Oyo East",
        "Oyo West",
        "Saki East",
        "Saki West",
        "Surulere"
    ],
    Plateau: [
        "Barikin Ladi",
        "Bassa",
        "Bokkos",
        "Jos East",
        "Jos North",
        "Jos South",
        "Kanam",
        "Kanke",
        "Langtang North",
        "Langtang South",
        "Mangu",
        "Mikang",
        "Pankshin",
        "Qua'an Pan",
        "Riyom",
        "Shendam",
        "Wase"
    ],
    Rivers: [
        "Abua/Odual",
        "Ahoada East",
        "Ahoada West",
        "Akuku Toru",
        "Andoni",
        "Asari-Toru",
        "Bonny",
        "Degema",
        "Emohua",
        "Eleme",
        "Etche",
        "Gokana",
        "Ikwerre",
        "Khana",
        "Obio/Akpor",
        "Ogba/Egbema/Ndoni",
        "Ogu/Bolo",
        "Okrika",
        "Omumma",
        "Opobo/Nkoro",
        "Oyigbo",
        "Port-Harcourt",
        "Tai"
    ],
    Sokoto: [
        "Binji",
        "Bodinga",
        "Dange-shnsi",
        "Gada",
        "Goronyo",
        "Gudu",
        "Gawabawa",
        "Illela",
        "Isa",
        "Kware",
        "kebbe",
        "Rabah",
        "Sabon birni",
        "Shagari",
        "Silame",
        "Sokoto North",
        "Sokoto South",
        "Tambuwal",
        "Tqngaza",
        "Tureta",
        "Wamako",
        "Wurno",
        "Yabo"
    ],
    Taraba: [
        "Ardo-kola",
        "Bali",
        "Donga",
        "Gashaka",
        "Cassol",
        "Ibi",
        "Jalingo",
        "Karin-Lamido",
        "Kurmi",
        "Lau",
        "Sardauna",
        "Takum",
        "Ussa",
        "Wukari",
        "Yorro",
        "Zing"
    ],
    Yobe: [
        "Bade",
        "Bursari",
        "Damaturu",
        "Fika",
        "Fune",
        "Geidam",
        "Gujba",
        "Gulani",
        "Jakusko",
        "Karasuwa",
        "Karawa",
        "Machina",
        "Nangere",
        "Nguru Potiskum",
        "Tarmua",
        "Yunusari",
        "Yusufari"
    ],
    Zamfara: [
        "Anka",
        "Bakura",
        "Birnin Magaji",
        "Bukkuyum",
        "Bungudu",
        "Gummi",
        "Gusau",
        "Kaura",
        "Namoda",
        "Maradun",
        "Maru",
        "Shinkafi",
        "Talata Mafara",
        "Tsafe",
        "Zurmi"
    ]
}
export const jobTitle =
    [
        'Accountant',
        'Admin',
        'Driver',
        'Field Supervisor',
        'Generator Technician',
        'Lawyer',
        'Procurement Officer',
        'Security Officer',
        'SuperAdmin',
        'User',
    ]
export const employmentType =
    [
        'FullTime',
        'Contract',
        'Trainee',
    ]
export const sitesData = {
    'Birnin-Gwari': [
        "BRU001",
        "BGR007",
        "BGR005",
        "BGR003",
        "BGR002",
        "BGR001",
        "KOM001"
    ],
    'Kaduna-Central': [
        "KAD020",
        "KAD037",
        "KAD038",
        "KAD052",
        "KAD055",
        "KAD056",
        "KAD064",
        "KAD071",
        "KAD072",
        "KAD081",
        "KAD103",
        "TNA013"
    ],
    Zaria: [
        "ZAR001",
        "ZAR002",
        "ZAR003",
        "ZAR004",
        "ZAR005",
        "ZAR006",
        "ZAR007",
        "ZAR012",
        "ZAR014",
        "ZAR015",
        "ZAR017",
        "ZAR019",
        "ZAR026",
        "ZAR028",
        "ZAR029",
        "ZAR032",
        "ZAR033",
        "ZAR045",
        "ZAR048",
        "ZAR049",
        "ZAR050",
        "TAB008",
        "TNB010",
        "TNB011",
        "KZK015",
        "KZK016",
        "KZK046",
        "KZK009",
        "KZK010",
        "KZK011",
        "KZK012",
        "KZK013",
        "KZK014",
        "KZK017",
        "KZK018",
        "KZK019",
        "KZK030",
        "KZK031",
        "KZK801",
        "MKF002",
        "SBA001",
        "SBA002",
        "SBA003",
        "SBA004",
        "MTR001",
        "MTR002"
    ],
}
export const siteStates = [
    'Kaduna',
]
export const sex = [
    'Female',
    'Male',
]
export const martialStatus = [
    'Single',
    'Married',
    'Divorced',
    'Widowed',
]
export const title = [
    'Miss',
    'Mr',
    'Mrs',
]
export const religionIdentity = [
    'Christianity',
    'Islam',
    'Others',
]
export const Countries = [
    'Nigeria',
]
export const nextOfKinRelationship = [
    'Father',
    'Mother',
    'Brother',
    'Sister',
    'Son',
    'Daughter',
    'Spouse',
    'Uncle',
    'Aunt',
    'Cousin',
    'Nephew',
    'Niece',
    'Grandfather',
    'Grandmother',
    'Others',
]

export const userData = [
    {
        "id": 1,
        "firstName": "Breanne",
        "lastName": "Alastair",
        "email": "balastair0@netvibes.com",
        "role": "Female"
    }, {
        "id": 2,
        "firstName": "Ursa",
        "lastName": "Iggalden",
        "email": "uiggalden1@intel.com",
        "role": "Female"
    }, {
        "id": 3,
        "firstName": "Eugenio",
        "lastName": "McGuggy",
        "email": "emcguggy2@google.fr",
        "role": "Male"
    }, {
        "id": 4,
        "firstName": "Aaron",
        "lastName": "Plumb",
        "email": "aplumb3@irs.gov",
        "role": "Male"
    }, {
        "id": 5,
        "firstName": "Rickey",
        "lastName": "Dy",
        "email": "rdy4@slideshare.net",
        "role": "Genderfluid"
    }, {
        "id": 6,
        "firstName": "Clayborn",
        "lastName": "Curphey",
        "email": "ccurphey5@washingtonpost.com",
        "role": "Male"
    }, {
        "id": 7,
        "firstName": "Avis",
        "lastName": "Clemmey",
        "email": "aclemmey6@360.cn",
        "role": "Female"
    }, {
        "id": 8,
        "firstName": "Noach",
        "lastName": "Soro",
        "email": "nsoro7@digg.com",
        "role": "Male"
    }, {
        "id": 9,
        "firstName": "Josy",
        "lastName": "MacCaughey",
        "email": "jmaccaughey8@imdb.com",
        "role": "Female"
    }, {
        "id": 10,
        "firstName": "Forest",
        "lastName": "Boak",
        "email": "fboak9@dailymail.co.uk",
        "role": "Male"
    }, {
        "id": 11,
        "firstName": "Dame",
        "lastName": "Spoure",
        "email": "dspourea@apple.com",
        "role": "Male"
    }, {
        "id": 12,
        "firstName": "Jacklyn",
        "lastName": "Rizzardi",
        "email": "jrizzardib@example.com",
        "role": "Non-binary"
    }, {
        "id": 13,
        "firstName": "Nata",
        "lastName": "Truggian",
        "email": "ntruggianc@e-recht24.de",
        "role": "Genderfluid"
    }, {
        "id": 14,
        "firstName": "Tammie",
        "lastName": "Summerell",
        "email": "tsummerelld@disqus.com",
        "role": "Female"
    }, {
        "id": 15,
        "firstName": "Shea",
        "lastName": "Arsey",
        "email": "sarseye@4shared.com",
        "role": "Polygender"
    }, {
        "id": 16,
        "firstName": "Eamon",
        "lastName": "Maccaig",
        "email": "emaccaigf@bigcartel.com",
        "role": "Male"
    }, {
        "id": 17,
        "firstName": "Winifield",
        "lastName": "Tonry",
        "email": "wtonryg@cisco.com",
        "role": "Male"
    }, {
        "id": 18,
        "firstName": "Bary",
        "lastName": "Gainseford",
        "email": "bgainsefordh@archive.org",
        "role": "Male"
    }, {
        "id": 19,
        "firstName": "Trenna",
        "lastName": "La Torre",
        "email": "tlatorrei@wordpress.com",
        "role": "Female"
    }, {
        "id": 20,
        "firstName": "Tracie",
        "lastName": "Summerside",
        "email": "tsummersidej@home.pl",
        "role": "Female"
    }, {
        "id": 21,
        "firstName": "Bendite",
        "lastName": "Amburgy",
        "email": "bamburgyk@ibm.com",
        "role": "Female"
    }, {
        "id": 22,
        "firstName": "Fayth",
        "lastName": "Trow",
        "email": "ftrowl@theglobeandmail.com",
        "role": "Female"
    }, {
        "id": 23,
        "firstName": "Ambrosio",
        "lastName": "Galsworthy",
        "email": "agalsworthym@telegraph.co.uk",
        "role": "Male"
    }, {
        "id": 24,
        "firstName": "Doloritas",
        "lastName": "Hayward",
        "email": "dhaywardn@instagram.com",
        "role": "Female"
    }, {
        "id": 25,
        "firstName": "Gayelord",
        "lastName": "Lavalle",
        "email": "glavalleo@wikia.com",
        "role": "Male"
    }, {
        "id": 26,
        "firstName": "Marion",
        "lastName": "Clerke",
        "email": "mclerkep@tiny.cc",
        "role": "Female"
    }, {
        "id": 27,
        "firstName": "Leigh",
        "lastName": "Baskeyfield",
        "email": "lbaskeyfieldq@cnn.com",
        "role": "Female"
    }, {
        "id": 28,
        "firstName": "Massimiliano",
        "lastName": "Caine",
        "email": "mcainer@blogspot.com",
        "role": "Male"
    }, {
        "id": 29,
        "firstName": "Fowler",
        "lastName": "Greenhalgh",
        "email": "fgreenhalghs@redcross.org",
        "role": "Male"
    }, {
        "id": 30,
        "firstName": "Spike",
        "lastName": "Mabee",
        "email": "smabeet@narod.ru",
        "role": "Male"
    }, {
        "id": 31,
        "firstName": "Lorne",
        "lastName": "Yakunin",
        "email": "lyakuninu@xing.com",
        "role": "Male"
    }, {
        "id": 32,
        "firstName": "Cleveland",
        "lastName": "Oury",
        "email": "couryv@desdev.cn",
        "role": "Male"
    }, {
        "id": 33,
        "firstName": "Ebenezer",
        "lastName": "Oneill",
        "email": "eoneillw@ucsd.edu",
        "role": "Male"
    }, {
        "id": 34,
        "firstName": "Deloria",
        "lastName": "Puttan",
        "email": "dputtanx@webeden.co.uk",
        "role": "Female"
    }, {
        "id": 35,
        "firstName": "Percy",
        "lastName": "Woodworth",
        "email": "pwoodworthy@homestead.com",
        "role": "Male"
    }, {
        "id": 36,
        "firstName": "Barbee",
        "lastName": "Mollatt",
        "email": "bmollattz@comsenz.com",
        "role": "Female"
    }, {
        "id": 37,
        "firstName": "Adrea",
        "lastName": "Guiot",
        "email": "aguiot10@edublogs.org",
        "role": "Agender"
    }, {
        "id": 38,
        "firstName": "Danica",
        "lastName": "McGaw",
        "email": "dmcgaw11@ameblo.jp",
        "role": "Non-binary"
    }, {
        "id": 39,
        "firstName": "Delinda",
        "lastName": "Killingback",
        "email": "dkillingback12@mayoclinic.com",
        "role": "Female"
    }, {
        "id": 40,
        "firstName": "Scotti",
        "lastName": "O'Sharry",
        "email": "sosharry13@usgs.gov",
        "role": "Male"
    }, {
        "id": 41,
        "firstName": "Isador",
        "lastName": "Bithany",
        "email": "ibithany14@freewebs.com",
        "role": "Male"
    }, {
        "id": 42,
        "firstName": "Grete",
        "lastName": "Callicott",
        "email": "gcallicott15@mysql.com",
        "role": "Female"
    }, {
        "id": 43,
        "firstName": "Bradan",
        "lastName": "Thewles",
        "email": "bthewles16@lulu.com",
        "role": "Male"
    }, {
        "id": 44,
        "firstName": "Claudia",
        "lastName": "Hould",
        "email": "chould17@ustream.tv",
        "role": "Female"
    }, {
        "id": 45,
        "firstName": "Ashlie",
        "lastName": "Philipeaux",
        "email": "aphilipeaux18@jigsy.com",
        "role": "Female"
    }, {
        "id": 46,
        "firstName": "Franchot",
        "lastName": "Olfert",
        "email": "folfert19@adobe.com",
        "role": "Male"
    }, {
        "id": 47,
        "firstName": "Donn",
        "lastName": "Gonnely",
        "email": "dgonnely1a@oakley.com",
        "role": "Genderfluid"
    }, {
        "id": 48,
        "firstName": "Wilfred",
        "lastName": "Gross",
        "email": "wgross1b@cocolog-nifty.com",
        "role": "Male"
    }, {
        "id": 49,
        "firstName": "Dorelia",
        "lastName": "Pendlington",
        "email": "dpendlington1c@google.ca",
        "role": "Female"
    }, {
        "id": 50,
        "firstName": "Maurie",
        "lastName": "Lacrouts",
        "email": "mlacrouts1d@quantcast.com",
        "role": "Bigender"
    }, {
        "id": 51,
        "firstName": "Molli",
        "lastName": "Joder",
        "email": "mjoder1e@tripadvisor.com",
        "role": "Female"
    }, {
        "id": 52,
        "firstName": "Gualterio",
        "lastName": "Pudden",
        "email": "gpudden1f@nba.com",
        "role": "Polygender"
    }, {
        "id": 53,
        "firstName": "Meggy",
        "lastName": "Fidele",
        "email": "mfidele1g@indiatimes.com",
        "role": "Female"
    }, {
        "id": 54,
        "firstName": "Pauletta",
        "lastName": "Brouard",
        "email": "pbrouard1h@bing.com",
        "role": "Female"
    }, {
        "id": 55,
        "firstName": "Eartha",
        "lastName": "Duckels",
        "email": "educkels1i@moonfruit.com",
        "role": "Female"
    }, {
        "id": 56,
        "firstName": "Chauncey",
        "lastName": "Ilchuk",
        "email": "cilchuk1j@ning.com",
        "role": "Male"
    }, {
        "id": 57,
        "firstName": "Melvin",
        "lastName": "Creavin",
        "email": "mcreavin1k@i2i.jp",
        "role": "Male"
    }, {
        "id": 58,
        "firstName": "Clarita",
        "lastName": "Dovinson",
        "email": "cdovinson1l@npr.org",
        "role": "Female"
    }, {
        "id": 59,
        "firstName": "Gearalt",
        "lastName": "Dyche",
        "email": "gdyche1m@netscape.com",
        "role": "Male"
    }, {
        "id": 60,
        "firstName": "Greggory",
        "lastName": "Beall",
        "email": "gbeall1n@chron.com",
        "role": "Male"
    }, {
        "id": 61,
        "firstName": "Horst",
        "lastName": "Livett",
        "email": "hlivett1o@globo.com",
        "role": "Male"
    }, {
        "id": 62,
        "firstName": "Ester",
        "lastName": "Radish",
        "email": "eradish1p@prlog.org",
        "role": "Agender"
    }, {
        "id": 63,
        "firstName": "Domenico",
        "lastName": "Pattington",
        "email": "dpattington1q@aol.com",
        "role": "Genderqueer"
    }, {
        "id": 64,
        "firstName": "Owen",
        "lastName": "Dillestone",
        "email": "odillestone1r@cmu.edu",
        "role": "Male"
    }, {
        "id": 65,
        "firstName": "Jeannette",
        "lastName": "Beardsdale",
        "email": "jbeardsdale1s@technorati.com",
        "role": "Female"
    }, {
        "id": 66,
        "firstName": "Ezri",
        "lastName": "Halson",
        "email": "ehalson1t@google.fr",
        "role": "Male"
    }, {
        "id": 67,
        "firstName": "Keri",
        "lastName": "Cullin",
        "email": "kcullin1u@stumbleupon.com",
        "role": "Female"
    }, {
        "id": 68,
        "firstName": "Sarita",
        "lastName": "Down",
        "email": "sdown1v@un.org",
        "role": "Female"
    }, {
        "id": 69,
        "firstName": "Boris",
        "lastName": "Strong",
        "email": "bstrong1w@163.com",
        "role": "Male"
    }, {
        "id": 70,
        "firstName": "Boigie",
        "lastName": "Losebie",
        "email": "blosebie1x@pagesperso-orange.fr",
        "role": "Male"
    }, {
        "id": 71,
        "firstName": "Reuven",
        "lastName": "Duckitt",
        "email": "rduckitt1y@mtv.com",
        "role": "Male"
    }, {
        "id": 72,
        "firstName": "Waiter",
        "lastName": "Baike",
        "email": "wbaike1z@gmpg.org",
        "role": "Non-binary"
    }, {
        "id": 73,
        "firstName": "Danielle",
        "lastName": "Romme",
        "email": "dromme20@webnode.com",
        "role": "Genderqueer"
    }, {
        "id": 74,
        "firstName": "Tabbitha",
        "lastName": "Reeks",
        "email": "treeks21@youtube.com",
        "role": "Non-binary"
    }, {
        "id": 75,
        "firstName": "Freeman",
        "lastName": "Izzard",
        "email": "fizzard22@webmd.com",
        "role": "Male"
    }, {
        "id": 76,
        "firstName": "Jamal",
        "lastName": "Mauchline",
        "email": "jmauchline23@stanford.edu",
        "role": "Male"
    }, {
        "id": 77,
        "firstName": "Kristoforo",
        "lastName": "Bucknill",
        "email": "kbucknill24@photobucket.com",
        "role": "Male"
    }, {
        "id": 78,
        "firstName": "Jose",
        "lastName": "Marklund",
        "email": "jmarklund25@wired.com",
        "role": "Male"
    }, {
        "id": 79,
        "firstName": "Neddy",
        "lastName": "McGonigal",
        "email": "nmcgonigal26@miibeian.gov.cn",
        "role": "Male"
    }, {
        "id": 80,
        "firstName": "Zebadiah",
        "lastName": "Maudlen",
        "email": "zmaudlen27@nasa.gov",
        "role": "Non-binary"
    }, {
        "id": 81,
        "firstName": "Valera",
        "lastName": "Nund",
        "email": "vnund28@npr.org",
        "role": "Female"
    }, {
        "id": 82,
        "firstName": "Beltran",
        "lastName": "Peagram",
        "email": "bpeagram29@paginegialle.it",
        "role": "Male"
    }, {
        "id": 83,
        "firstName": "Sharyl",
        "lastName": "Rosterne",
        "email": "srosterne2a@1und1.de",
        "role": "Female"
    }, {
        "id": 84,
        "firstName": "Tildy",
        "lastName": "Pattullo",
        "email": "tpattullo2b@utexas.edu",
        "role": "Female"
    }, {
        "id": 85,
        "firstName": "Laura",
        "lastName": "Richardes",
        "email": "lrichardes2c@geocities.com",
        "role": "Female"
    }, {
        "id": 86,
        "firstName": "Cristy",
        "lastName": "Swalwell",
        "email": "cswalwell2d@va.gov",
        "role": "Female"
    }, {
        "id": 87,
        "firstName": "Tonnie",
        "lastName": "Gilstin",
        "email": "tgilstin2e@pcworld.com",
        "role": "Male"
    }, {
        "id": 88,
        "firstName": "Valeda",
        "lastName": "Lunbech",
        "email": "vlunbech2f@adobe.com",
        "role": "Female"
    }, {
        "id": 89,
        "firstName": "Conney",
        "lastName": "Le feaver",
        "email": "clefeaver2g@stanford.edu",
        "role": "Male"
    }, {
        "id": 90,
        "firstName": "Ninon",
        "lastName": "Blaxlande",
        "email": "nblaxlande2h@whitehouse.gov",
        "role": "Polygender"
    }, {
        "id": 91,
        "firstName": "Rubina",
        "lastName": "Dawton",
        "email": "rdawton2i@sourceforge.net",
        "role": "Female"
    }, {
        "id": 92,
        "firstName": "Billye",
        "lastName": "Sperry",
        "email": "bsperry2j@redcross.org",
        "role": "Agender"
    }, {
        "id": 93,
        "firstName": "Jackie",
        "lastName": "Abell",
        "email": "jabell2k@nytimes.com",
        "role": "Male"
    }, {
        "id": 94,
        "firstName": "Ly",
        "lastName": "Klaas",
        "email": "lklaas2l@intel.com",
        "role": "Male"
    }, {
        "id": 95,
        "firstName": "Wini",
        "lastName": "Wrighton",
        "email": "wwrighton2m@drupal.org",
        "role": "Female"
    }, {
        "id": 96,
        "firstName": "Olivie",
        "lastName": "Whilde",
        "email": "owhilde2n@army.mil",
        "role": "Female"
    }, {
        "id": 97,
        "firstName": "Lela",
        "lastName": "Domenicone",
        "email": "ldomenicone2o@home.pl",
        "role": "Female"
    }, {
        "id": 98,
        "firstName": "Myrle",
        "lastName": "MacLucais",
        "email": "mmaclucais2p@is.gd",
        "role": "Female"
    }, {
        "id": 99,
        "firstName": "Alexine",
        "lastName": "Pordall",
        "email": "apordall2q@over-blog.com",
        "role": "Female"
    }, {
        "id": 100,
        "firstName": "Erminie",
        "lastName": "Guwer",
        "email": "eguwer2r@auda.org.au",
        "role": "Female"
    }

]
