import { Inter } from "next/font/google";
import "../globals.css";
import Nav from "@/components/Navigation/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function EntryLayout({ children }) {
  return (
            <>
                <Nav/>
                {children}
            </>
  );
}
